stages:
    - test


python:
    stage: test
    image: python:3.6
    services:
        - name: liminspace/mjml-tcpserver:latest
          alias: mjml
    before_script:
        - pip3 install -e .
    script:
        - python3 runtests.py

