stages:
    - test


python:
    stage: test
    image: python:3.6
    services:
        - name: liminspace/mjml-tcpserver:latest
          alias: mjml
        - postgres:9.6
    variables:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ""
        POSTGRES_HOST_AUTH_METHOD: trust
    before_script:
        - pip3 install -e .
    script:
        - python3 runtests.py

