stages:
    - test


.python:
    stage: test
    services:
        - name: liminspace/mjml-tcpserver:latest
          alias: mjml
        - postgres:9.6
    variables:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ""
        POSTGRES_HOST_AUTH_METHOD: trust
    before_script:
        - pip3 install psycopg2-binary~=2.8.0 -e .
    script:
        - python3 runtests.py

three_six:
    extends: .python
    image: python:3.6
    variables:
        TEST_DB: py_36

three_seven:
    extends: .python
    image: python:3.7
    variables:
        TEST_DB: py_37

three_eight:
    extends: .python
    image: python:3.8
    variables:
        TEST_DB: py_38