version: "3"

services:
    postgres:
        environment:
            POSTGRES_DB: birdsong
            POSTGRES_USER: birdsong_dev
            POSTGRES_PASSWORD: password
        restart: always
        image: postgres:9.6
        expose:
            - "5432"
    birdsong:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        command: django-admin runserver 0.0.0.0:8080
        links:
            - mjml
            - mail
            - postgres
        ports:
            - "8080:8080"
        container_name: 'birdsong_dev'
        working_dir: '/srv'
        volumes:
            - './tests:/srv/tests'
            - './birdsong:/srv/birdsong'
            - './settings_dev.py:/srv/settings_dev.py'
            # - './local.sqlite3:/srv/local.sqlite3'
    mjml:
        image: liminspace/mjml-tcpserver:latest
        restart: always
        ports:
            - "28101"
        container_name: 'birdsong_mjml'

    mail:
        image: djfarrelly/maildev
        ports:
            - "8081:80"
        container_name: 'birdsong_mail'

